### ISSUE TITLE
Nit: WebDriver has a way to press keyboard keys for the whole page

### ISSUE THREAD

**Issue by WestonThayer** [bocoup/aria-at-automation#5]
https://github.com/bocoup/aria-at-automation#press-keyboard-keys

> The second detail is conceptual: keys pressed by a screen reader users are not necessarily directed at any particular element, so the WebDriver command's required element reference would be superfluous in many cases.

Just a small nit, the [Perform Actions command](https://w3c.github.io/webdriver/#dfn-perform-actions) can be used to generically inject input to the page that's not targeted at a specific element. I sometimes use this for testing keyboard accessibility. Not that it changes your conclusion.

**Comment by jugglinmike** [comment]
Thanks for pointing this out! I've opened gh-7 to remove that claim.
